Repository TechNinjass/midall-backend, pull requests merged in 2023-04, with the labels that each got.

#36 Add CORS application
  flaskr/app.py
  requirements.txt
Labels: back-end, front-end

#37 Feature 33
  README.md
  flaskr/app.py
  flaskr/cloud_connection/aws_connection.py
  flaskr/cloud_connection/drive_connection.py
  flaskr/job_scheduler.py
  flaskr/models/__init__.py
  flaskr/models/file.py
  flaskr/resources/file_transfer.py
  flaskr/resources/list_files_aws.py
  flaskr/resources/list_files_drive.py
  flaskr/routes.py
  flaskr/services/file.py
  flaskr/token.json
  tests/test_connection_drive.py
Labels: back-end

#47 Initial config db
  flaskr/config_app.py
  flaskr/db.py
Labels: back-end, banco de dados

#48 Feature ci
  flaskr/app.py
  flaskr/cloud/azure.py
  flaskr/cloud/drive.py
  flaskr/cloud_connection/aws_connection.py
  flaskr/cloud_connection/credentials.json
  flaskr/cloud_connection/drive_connection.py
  flaskr/config_app.py
  flaskr/db.py
  flaskr/job_scheduler.py
  flaskr/resources/azure_connection.py
  flaskr/resources/azure_list_files.py
  flaskr/resources/drive_connection.py
  flaskr/resources/drive_list_files.py
  flaskr/resources/file_transfer.py
  flaskr/resources/list_files_aws.py
  flaskr/resources/list_files_drive.py
  flaskr/routes.py
  flaskr/services/file.py
  flaskr/token.json
  requirements.txt
  tests/test_connection_drive.py
  tests/test_drive.py
Labels: back-end, cloud

#51 Feature 50
  flaskr/cloud/azure.py
  flaskr/cloud/drive.py
  flaskr/services/file.py
Labels: back-end, cloud

#52 Feature 2
  flaskr/models/__init__.py
  flaskr/models/file_transfer.py
Labels: back-end, banco de dados

#53 Feature 51
  flaskr/app.py
  flaskr/cloud/azure.py
  flaskr/cloud/drive.py
  flaskr/config_app.py
  flaskr/migrate.py
  flaskr/migrations/README
  flaskr/migrations/alembic.ini
  flaskr/migrations/env.py
  flaskr/migrations/script.py.mako
  flaskr/migrations/versions/d02cc691b80e_initial_migration.py
  flaskr/services/file.py
Labels: back-end, banco de dados, cloud

#54 Alteração de token, informações do arquivo
  flaskr/cloud/azure.py
Labels: back-end, cloud

#55 test save files in transfer
  tests/test_azure.py
  tests/test_drive.py
Labels: back-end, cloud

#56 Teste test_list_files_empty_container
  flaskr/services/file.py
  requirements.txt
  tests/test_azure.py
Labels: back-end, cloud

#57 fix job in function transfer and add libs in r.txt
  flaskr/app.py
  flaskr/cloud/azure.py
  flaskr/job_scheduler.py
  flaskr/services/file.py
  requirements.txt
Labels: back-end, banco de dados, cloud, documentação

#61 update ci
  .github/workflows/github-ci.yml
Labels: back-end

#62 Feature 62
  flaskr/cloud/azure.py
  requirements.txt
Labels: back-end, cloud
